wjdp/htmltest

README.md, htmldoc/document.go, htmltest/check-generic.go, htmltest/check-meta.go, htmltest/check-meta_test.go, htmltest/fixtures/meta/refresh-content-blank.html, htmltest/fixtures/meta/refresh-content-invalid-malformed.html, htmltest/fixtures/meta/refresh-content-invalid-redirect.html, htmltest/fixtures/meta/refresh-content-invalid-refresh.html, htmltest/fixtures/meta/refresh-content-missing.html, htmltest/fixtures/meta/refresh-external-broken.html, htmltest/fixtures/meta/refresh-external-valid.html, htmltest/fixtures/meta/refresh-internal-broken.html, htmltest/fixtures/meta/refresh-internal-valid.html, htmltest/fixtures/meta/refresh-refresh.html, htmltest/htmltest.go, htmltest/options.go
Add `meta` tags to NodesOfInterest.
Split generic ref checking from checkGeneric, make hT.checkGenericRef function.
Create check-meta.go, hT.checkMeta function. This checks meta tags.
Forward meta tags to this function when scanning through NodesOfInterest.
If a meta tag has `http-equiv == "refresh"` we check several things now:
- Is the content attr present and non-blank
- Is the first term in the content attr a positive integer
- Is the separator `;url=`
- Is what follows `;url`= a valid reference
Add options `CheckMeta`, `CheckGeneric` and `CheckMetaRefresh`.
Will close #20 and sets us up for opengraph checks, re #7.
=> Check meta refresh tags

README.md, htmltest/check-link.go, htmltest/check-link_test.go, htmltest/options.go
Ignore `href="#"` via:
- turning off `CheckInternalHash`
- turning on `IgnoreInternalEmptyHash`
See https://github.com/wjdp/htmltest/issues/30
=> Ignore blank internal hashes via options

buildme.sh, htmldoc/document.go, htmldoc/document_store.go, htmldoc/util.go, htmltest/check-link.go, htmltest/htmltest.go, htmltest/util.go, main.go, output/error.go
- Calls to package specific checkErr methods replaced with single CheckErrorPanic() method.
- Addition of CheckErrorGeneric(), same as CheckErrorPanic but without the panic call, prints error and calls os.Exit(1).
- Addition of AbortWith method, handles exiting nicely -- print red and exit with os.Exit(1). CheckErrorGeneric calls this.
- Replacement of common errors (missing CLI args, missing config file) calling panic -> CheckErrorGeneric or AbortWith.
- Will close #17.
Example when calling program without path or config file.
```
~ ❯❯❯ htmltest
No path provided & .htmltest.yml does not exist.
See htmltest -h for usage.
```
=> Cleaner errors, implement output package.

.travis.yml, htmltest/options.go, main.go, output/print.go
This is a bit multi-faceted due a number of small additions showcasing a bug, which then was squished using new debug viewing features.
- Add short versions of --log-level, --conf and --version, -l, -c and -v.
- Merge CLI options with config file options, CLI options take presidence.
- Add -s, --skip-external option. Disables CheckExternal, rather useful when running locally and calling many times.
- Improve error messages when config file is specified but not found, prior it would complain that a path or generic config file did not exist not very useful!
- When LogLevel is debug (0) the options struct gets dumped to output. Rather useful when debugging options resolution:
```
htmltest started at 06:07:10 on htmldoc/fixtures/documents …
```
=> CLI wrangling, add some options, fix some bugs.

htmltest/htmltest.go, main.go
- Allow passing a file in as <path> from the CL. Detect file/dir in main.go and pass correct options to htmltest.
```
~/g/s/g/w/htmltest ❯❯❯ go run main.go htmltest/fixtures/meta/refresh-internal-broken.html -s                                                   cli-wrangling ◼
Skipping the checking of external links.
htmltest started at 05:41:53 on htmltest/fixtures/meta
========================================================================
refresh-internal-broken.html
target does not exist --- refresh-internal-broken.html --> nope.html
========================================================================
✘✘✘ failed in 644.93µs
1 errors in 12 documents
```
- Add CountDocuments func to htmltest, allows passthru of doumentStore count for CLI stats. Print CountDocuments in pass and fail …
=> Further CLI wrangling, allow both file and dir as <path>, extra stats.

README.md, htmldoc/document.go, htmldoc/fixtures/conf.yaml, htmldoc/fixtures/documents/dir2/index.html, htmltest/check-doctype.go, htmltest/check-doctype_test.go, htmltest/fixtures/doctype/doctype-html4.html, htmltest/fixtures/doctype/doctype-html5.html, htmltest/fixtures/doctype/doctype-missing.html, htmltest/fixtures/doctype/doctype-not-first.html, htmltest/fixtures/doctype/doctype-xhtml.html, htmltest/htmltest.go, htmltest/options.go, htmltest/test_helpers_test.go, issues/issue_store.go
- New options: CheckDoctype and EnforceHTML5
- When CheckDoctype is true we check that a doctype exists.
- When EnforceHTML5 is true we check the doctype matches the format for HTML5.
The golang htmlpackage does most of the heavy lifting for this one. For example it ignores doctypes which are not the first node in the document.
=> Implement document type checking (DOCTYPE)

README.md, htmltest/htmltest.go, htmltest/options.go
- Allow custom file extension via `FileExtension` option.
- When FilePath is set extract and use file extension from that.
=> Add FileExtension option, defaults to ".html"

htmltest/check-link_test.go, htmltest/fixtures/links/https-valid-h2.html, htmltest/htmltest.go
Go's HTTP lib wil negotiate HTTP/2 with a server, but then cannot fall back to H1 if H2 is having issues. Turn of H2, we don't really mind.
Will close #49
=> Update TLS conf to actually disable H2

htmltest/check-link.go, htmltest/check-link_test.go, htmltest/fixtures/links/link-rel-dns-prefetch.html
Will close #40 
Our current behaviour for checking these links is incorrect. If we were to implement anything it would check the link is formed correctly and DNS resolves for it. No HTTP checks should take place.
In lieu of that for now we disable checks running against these links.
=> Ignore links with rel=dns-prefetch

htmltest/check-link.go
Hello, attempt to fix #59.
**Context:** First thing, the link which generate the error is `/products/desktop/11/release-notes/#low-quality` ~ l.3032 from @miltador.
**Process:** `htmltest` will enter to the method `checkInternalHash` then to `refDoc, _ := hT.documentStore.ResolveRef(ref)` which return `nil, false` because there is no match (method `func (dS *DocumentStore) ResolvePath(refPath string) (*Document, bool) `), but methods are called from the struct and one of them try to acces to one of these properties as the mutex, and panic.
**Fix:** To prevent this error I suggest to check segment only if the file exist
note: naming `segment` would be not better than `hash` in `checkInternalHash` ?
=> Ensure file exist before checking segment

htmltest/check-img.go, htmltest/check-img_test.go, htmltest/fixtures/images/usemapEmpty.html, htmltest/fixtures/images/usemapInButton.html, htmltest/fixtures/images/usemapInLink.html, htmltest/fixtures/images/usemapMapDoesNotExist.html, htmltest/fixtures/images/usemapReferenceInvalid.html, htmltest/fixtures/images/usemapValid.html
=> Check usemap attribute of <img> elements

coverage.sh
Just running `go test -cover` will only report the coverage on files that are tested.
Using `go test -coverpkg=./...` the tests report their impact on the coverage of the project overall rather than just the covered file.
`go tool cover` command has also been added to view the coverage from within builds.
It is expected from my local testing that coverage will drop from 96.4% to 84.3%.
This is a contribution back based on an adaptation of this script for another project, the final line also allows coverage reporting in GitLab natively.
=> Improve coverage reporting accuracy with -coverpkg

htmltest/check-link.go, htmltest/check-link_test.go, htmltest/fixtures/links/root-link-explicit.html
=> Allow linking directly to index.html without a trailing slash

htmltest/check-link.go, htmltest/check-link_test.go
Previously, if "a.html" linked to an ignored directory "b", htmltest
would complain that "b" did not contain index.html, even if it did.
=> Don't complain if linking to ignored dir

.gitignore, .goreleaser.yml, .travis.yml, appveyor.yml, build.sh, main.go
Implements the goreleaser part of #80 
- Remove use of travis GH releases deployment method
- Add goreleaser config
- Add goreleaser as a travis deploy script
- Swap `buildDate` ldflag with just `date` to align with goreleaser defaults.
=> Swap custom build with goreleaser

htmldoc/document.go, htmldoc/document_store.go, htmltest/check-generic.go, htmltest/check-img.go, htmltest/check-img_test.go, htmltest/check-link.go, htmltest/check-link_test.go, htmltest/check-meta.go, htmltest/check-script.go, htmltest/check-script_test.go, htmltest/fixtures/images/ignorableImagesChildren.html, htmltest/fixtures/links/ignorableLinksChildren.html, htmltest/fixtures/scripts/scriptIgnorableChildren.html, htmltest/htmltest.go
The IgnoreTagAttribute used to only apply to the element it was applied to and was re-implemented on each check function.
Now we implement this check when we parse the document and completely ignore any element (and their children) where we find this attribute.
This PR implements #95
=> Make IgnoreTagAttribute ignore both the entire element and all its children

htmltest/check-meta.go, htmltest/check-meta_test.go, htmltest/fixtures/meta/issues/92.html
Will now raise an issue that meta url should not start with these characters as per spec
https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-refresh
> For meta elements with an http-equiv attribute in the Refresh state, the content attribute must have a value consisting either of:
>
> - just a valid non-negative integer, or
> - a valid non-negative integer, followed by a U+003B SEMICOLON character (;), followed by one or more ASCII whitespace, followed by a substring that is an ASCII case-insensitive match for the string "URL", followed by a U+003D EQUALS SIGN character (=), followed by a valid URL string that does not start with a literal U+0027 APOSTROPHE (') or U+0022 QUOTATION MARK (") character.
Fixes #92
=> Fix panic when meta refresh url starts with single or double quote

htmltest/check-img.go, htmltest/check-img_test.go, htmltest/fixtures/images/altBlank.html
Previously would only ignore alts if missing, now does what it says it does and disables all alt checks.
Fixes #115
=> Fix for IgnoreAltBlank when alt=""

README.md, htmltest/check-link.go, htmltest/check-link_test.go, htmltest/options.go
Thanks for the useful project! I have started trying to use it with Hugo. However, my site uses Hugo templates and being unable to disable the empty href check makes it a non-starter. 
Please review this simple PR for adding an option for that.
=> Add IgnoreEmptyHref option

htmldoc/reference.go, htmldoc/reference_test.go, htmltest/check-generic.go, htmltest/check-img.go, htmltest/check-link.go, htmltest/check-meta.go, htmltest/check-script.go
Will also handle other reference errors more gracefully.
Closes #127.
=> Fix failing test with invalid port by adding popper handling of the error

htmltest/check-link.go, htmltest/check-link_test.go, htmltest/fixtures/links/https-incomplete-chain.html, htmltest/util.go
Generate an error instead of a warning as these are likely due to issues with a remote server out of your control and will work in most browsers.
Closes #130
=> Add the ability for html test to accept servers using AIA.

htmltest/check-link_test.go
VCR doesn't seem to encode enough for this test to pass with the mocked result.
=> Disable VCR for TestAnchorExternalHTTPSMissingChain

.goreleaser.yml, README.md
re https://github.com/wjdp/htmltest/issues/141
- builds binaries for OpenBSD during release
- adds notes on installation in README
=> Support for installing on OpenBSD

README.md, htmltest/check-generic.go, htmltest/check-link.go, htmltest/check-link_test.go, htmltest/options.go
Do let me know if it is useful, we particularly required this while checking links for [julialang.org](https://julialang.org) site which has a large number of links.
I'll add tests and docs soon, if this idea looks good enough.
Closes https://github.com/wjdp/htmltest/issues/139
cc @wjdp
=> Add option: `IgnoreExternalBrokenLinks`

Dockerfile, README.md
This change specifies htmltest as the ENTRYPOINT command in the Dockerfile. This change makes it so that Docker concatenates the ENTRYPOINT and the CMD. The big benefit is that clients don't have to redundantly type the binary name when they run the Docker image.
Instead of this:
docker run -v /home/mike/htmltest:/test --rm wjdp/htmltest htmltest -l 3 -s
they can leave out the second 'htmltest' like this:
docker run -v /home/mike/htmltest:/test --rm wjdp/htmltest -l 3 -s
=> Using ENTRYPOINT to simplify docker run semantics

htmltest/options.go, htmltest/options_test.go
closes https://github.com/wjdp/htmltest/issues/145
=> fix: panic whith custom http headers

issues/issue.go, main.go
If set, this will turn off colourization of the output.
See https://no-color.org/
Fixes wjdp/htmltest#90
=> Respect the NO_COLOR environment variable if it is set.

htmltest/check-link.go, htmltest/test_helpers_test.go
Sometimes the error message from http.Client is different in Go 1.15 for client timeouts.
The messages causing issues contain "dial tcp" which was caught before Client.Timeout.
This fix just moves the handler for "Client.Timeout" above "dial tcp".
Will close #148
=> Fix flaky test (TestAnchorExternalHrefIPTimeout)

go.mod, go.sum, htmltest/check-link.go, htmltest/check-link_test.go, htmltest/fixtures/links/mailto_encoded.html, htmltest/fixtures/links/mailto_encoded_invalid.html
- We now check the format of emails using the https://github.com/badoux/checkmail package.
- We also decode the address which will fix #124.
=> Implement mailto email format checking (with url decoding)

htmldoc/document.go, htmldoc/document_test.go, htmltest/check-img_test.go, htmltest/check-link_test.go, htmltest/check-script_test.go, htmltest/fixtures/images/badImagesInPre.html, htmltest/fixtures/links/hash-in-pre-163.html, htmltest/fixtures/scripts/script_in_pre.html, htmltest/fixtures/vcr/links/anchors_in_pre.html.cassette, htmltest/fixtures/vcr/scripts/script_in_pre.html.cassette
Unsure where we got the idea to ignore HTML in `pre` and `code` tags. It was a mistake. This PR removes this exception and adjusts tests.
It will also fix #163
=> Stop ignoring the content of pre / code tags

htmltest/check-link_test.go, htmltest/htmltest_test.go
You can test this by running `unshare -n -r -- go test -short ./...`
=> Add missing skips for external access.

.gitignore, go.sum, htmldoc/document.go, htmldoc/document_store.go, htmldoc/document_store_test.go, htmldoc/reference.go, htmltest/check-link.go, htmltest/htmltest.go
This fix includes two things:
1. Check for `ok` value from `ResolveRef` in `checkInternalHash`. If a value was ignored but was a valid link, it would panic as it was not found.
2. Change the behaviour of `discoverRecurse` such that it keeps all found `Document`s, but adds a new `IgnoreTest` attribute such that we can track if it should be skipped on test, but still referenced in a test.
Closes #126
=> Fix panic when referencing ignored directories

README.md, htmltest/check-link.go, htmltest/check-link_test.go, htmltest/fixtures/links/brokenLinkFile.html
- Closes #109
- Solves the original request of #168
=> Apply IgnoreURLs regexs to internal and file URLs too

README.md, htmltest/check-img.go, htmltest/check-img_test.go, htmltest/fixtures/images/emptyImageAltTextExplicit.html, htmltest/options.go
Introduces a new configuration option, `IgnoreAltEmpty` for allowing alt attribute checks against images, while being more lenient with explicit empty alt attributes.  WAI instructs HTML practitioners to set an explicitly empty alt attribute for decorative images that offer no additional context or meaningful information to a page, so that they can be skipped by screen readers:
https://www.w3.org/WAI/tutorials/images/decorative/
Fixes #153
I have been using this on my own fork to validate https://vivanti.com/
=> IgnoreAltEmpty option for alt="" decorative images

htmltest/check-link.go
In large HTML files finding the blank href attributes in anchor tags
can be difficult. This change adds more details like the title and
body of the anchor to the error message to make it more obvious which
link is broken.
=> add details for blank href errors

README.md, htmldoc/attr.go, htmldoc/document.go, htmltest/fixtures/links/ignorableLinks.html, htmltest/fixtures/links/ignorableLinksChildren.html
Ingoring by tag attribute is helpful, but eg. docusaurus does not offer a good way to manipulate its theme. But it offers a way to always attach a custom class.
With this approach, we will reuse the IgnoreTagAttribute as a class name detection.
It isn't worth specifying an additional attribute for this use case, although the naming might be off now.
_Disclaimer_
I did not find a contributing guide, so I went ahead and created this pr. If you prefer to discuss this first in an issue, I will also gladly create one.
=> Add possibility to ignore based on existing class

htmltest/htmltest_test.go
In https://github.com/wjdp/htmltest/commit/d785ba51dd8b6a10ea60696ec4cb9d34f80c1b39, new tests were added that rely on network.
We're adding the tSkipShortExternal option to bypass them in -short mode.
=> Add tSkipShortExternal to the new network tests

.github/workflows/ci.yml, Dockerfile
I noticed that the Docker Hub image was only built for amd64.
This adds a linux/arm64 platform variant to the Docker image,
which makes htmltest run faster (no emulation) on ARM-based systems.
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>
=> release: multi-platform docker image

issues/issue_store_test.go, issues/issue_test.go
Go 1.24 testing now [vets that examples name an actual identifier](https://go.dev/doc/go1.24#vet), so these must be renamed to match, or specify a distinct suffix.
=> Fix invalid Example naming
